language: php
php:
  - 7.1
  - 7.2
  - 7.3

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install: composer update --prefer-lowest --no-interaction

script:
  - cp .env.example .env
  - 'if [ "$TRAVIS_SECURE_ENV_VARS" = "true" ]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.clover; fi'
  - 'if [ "$TRAVIS_SECURE_ENV_VARS" = "false" ]; then phpdbg -qrr vendor/bin/phpunit --exclude-group=large --coverage-clover=coverage.clover; fi'

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
